server:
  port: 10085
# 集群测试配置，后续删除
#mqtt:
#  port: 1884
#  data_path: moquette_store.h2
spring:
  application:
    # 应用名称
    name: plat-modules-broker
  main:
    allow-circular-references: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  redis:
    database: 13
    host: 222.212.88.142
    port: 6377
    password:
    timeout: 30000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
rocketmq:
  # RocketMQ NameServer 地址（可以配置多个，用分号分隔）
  name-server: 192.168.3.58:9876
  # 生产者配置
  producer:
    # 生产者组名称，建议全局唯一
    group: my-producer-group
    # 消息发送超时时间（单位：毫秒）
    send-message-timeout: 3000
    # 异步发送消息失败时的重试次数
    retry-times-when-send-async-failed: 2
    # 同步发送消息失败时的重试次数（默认 2 次）
    retry-times-when-send-failed: 2
    # 是否开启压缩，压缩阈值（单位：字节），0 表示不压缩
    compress-level: 5
    compress-threshold: 4096
  # 消费者配置
  consumer:
    consumer-group:
      server-message-group:
        topic: server-message-topic
      client-message-group:
        topic: client-message-topic
      session-message-group:
        topic: session-change-topic
    # 消费线程池中最大的线程数
    consume-thread-max: 20
    # 每次拉取消息的批量大小
    pull-batch-size: 32
    # 是否启用顺序消费
    enable-message-orderly: false
    # 如果需要设置延时消息的消费参数，也可以在这里配置
    delay-level: 3
#moquette:
#  auth:
#    type: http  # 认证方式: 暂时支持http，后续可扩展其他的方式
#    httpUrl: http://localhost:10085/api/mqtt/auth
#    httpTimeout: 3000
